### ISSUE TITLE
Examples do not build

### ISSUE THREAD

**Issue by p0nce** [SealabJaster/jcli#63]
Hello,

I don't manage to build an example.

<img width="753" alt="image" src="https://github.com/BradleyChatha/jcli/assets/1067485/50d133cf-f7f2-49c7-8565-5ec0015fdd7a">

```
DUB version 1.35.1, built on Jan  6 2024

LDC - the LLVM D compiler (1.36.0):   
based on DMD v2.106.1 and LLVM 17.0.6

DMD64 D Compiler v2.106.0-dirty
```

**Comment by p0nce** [comment]
Oh I see. I only saw the "examples" directory, not the "new_examples" directory. Why keep the old ones?

**Comment by BradleyChatha** [comment]
I can't fully remember why - I think I may have wanted to convert them over to the new API at some point.

I'm the first to admit that this library is not as well maintained as it really should be (I've been meaning to fix the README for like 2 **years** now).

Currently any energy I get to do some side work in D in my free time (which is scarce these days) is being spent on [juptune](https://github.com/Juptune/juptune) instead. Even lumars, my other main library, is lagging behind quite a bit :(

**Comment by BradleyChatha** [comment]
I can recommend [argparse](https://github.com/andrey-zherikov/argparse) if you're looking for a more active library. The author used to help out with JCLI, but moved on to create his own work.

**Comment by p0nce** [comment]
OK, thanks! It looked interesting
